source:      .
destination: ./_site
includes:    ./_includes
baseurl: ""  # GitHub Pages expects empty baseurl for user sites
url: "https://wtzhang99.github.io"

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-default-layout
  - jekyll-optional-front-matter

# GitHub Pages safe mode
safe: true

# Markdown settings
markdown: kramdown
highlighter: rouge

# Excerpt settings
excerpt_separator: <!--more-->

collections:
  projects:
    output: true
