source:      .
destination: ./_site
includes:    ./_includes
baseurl: https://wtzhang99.github.io
# baseurl: ""

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Excerpt settings
excerpt_separator: <!--more-->

collections:
  projects:
    output: true
